### PR TITLE
Iconify buffer names with all-the-icons-ivy

### PR DESCRIPTION
**Pull request by xwl**
When all-the-icons-ivy is available, add an icon (which represents the
file type) in front of the buffer name, such that it is easier to spot
the desired buffer to jump to.

### CODE REVIEW

**Comment by xwl** [comment]
BTW, there is a bug in frog-menu, i created a pull request there too: https://github.com/clemera/frog-menu/pull/11/commits/f50842351b4f9b23ce0c69243d85893c721a1d36

**Comment by waymondo** [comment]
Very nice. Can you append a blurb to the README or CHANGELOG about this?

**Comment by xwl** [comment]
Done. I upload a screenshot as well, if that is fine.

**Comment by waymondo** [comment]
Thanks!

**Pull request merged**
